export const UPDATE_ORDER = 'UPDATE_ORDER';
export const INITIALISE_ITEM_ORDER_WITH_NEWROW = 'INITIALISE_ITEM_ORDER_WITH_NEWROW';
export const INITIALISE_ITEM_ORDER_WITH_DEFAULT = 'INITIALISE_ITEM_ORDER_WITH_DEFAULT';
export const UPDATE_ITEM_ORDER = 'UPDATE_ITEM_ORDER';
export const REMOVE_ITEM_ORDER = 'REMOVE_ITEM_ORDER';
